<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GZCTF.Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GZCTF.GuestControl.Contracts\GZCTF.GuestControl.Contracts.csproj" />
    <ProjectReference Include="..\GZCTF.TeamLab.Contracts\GZCTF.TeamLab.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet" />
    <PackageReference Include="PacketDotNet" />
    <PackageReference Include="SharpPcap" />
  </ItemGroup>

</Project>
