<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <CollectCoverage>true</CollectCoverage>
    <Configurations>Debug;Release</Configurations>
    <ReleaseVersion>1.8.3</ReleaseVersion>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.runner.console" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GZCTF\GZCTF.csproj" />
    <ProjectReference Include="..\GZCTF.Agent\GZCTF.Agent.csproj" />
    <ProjectReference Include="..\GZCTF.EndpointSensor\GZCTF.EndpointSensor.csproj" />
    <ProjectReference Include="..\GZCTF.GuestControl.Contracts\GZCTF.GuestControl.Contracts.csproj" />
    <ProjectReference Include="..\GZCTF.GuestTelemetry\GZCTF.GuestTelemetry.csproj" />
    <ProjectReference Include="..\GZCTF.GuestSupervisor\GZCTF.GuestSupervisor.csproj" />
    <None Include="..\GZCTF\appsettings*" />
  </ItemGroup>
</Project>
