using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GZCTF.Migrations;

/// <summary>
/// Adds the Phase 4 schema without replacing or deleting existing business data.
/// </summary>
public partial class ExpandPhaseFourDatabaseGovernance : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE EXTENSION IF NOT EXISTS pgcrypto;

            ALTER TABLE "Logs" ALTER COLUMN "Id" TYPE bigint;
            DO $phase4$
            DECLARE sequence_name text;
            BEGIN
                sequence_name := pg_get_serial_sequence('"Logs"', 'Id');
                IF sequence_name IS NOT NULL THEN
                    EXECUTE format('ALTER SEQUENCE %s AS bigint', sequence_name);
                END IF;
            END
            $phase4$;

            ALTER TABLE "TeamLabTrafficFlows"
                ADD COLUMN IF NOT EXISTS "SourcePrefix" character varying(64),
                ADD COLUMN IF NOT EXISTS "DestinationPrefix" character varying(64),
                ADD COLUMN IF NOT EXISTS "Fingerprint" bytea;

            CREATE TABLE "DataGovernanceRuns" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DataSet" character varying(64) NOT NULL,
                "Operation" character varying(64) NOT NULL,
                "Status" smallint NOT NULL,
                "LeaseOwner" character varying(128) NOT NULL,
                "Cutoff" timestamp with time zone NOT NULL,
                "RowsRead" bigint NOT NULL,
                "RowsAggregated" bigint NOT NULL,
                "RowsDeleted" bigint NOT NULL,
                "PartitionName" character varying(128),
                "ErrorCode" character varying(128),
                "ErrorDetail" character varying(2048),
                "StartedAt" timestamp with time zone NOT NULL,
                "CompletedAt" timestamp with time zone
            );

            CREATE TABLE "DeploymentLifecycleAggregates" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BucketStart" timestamp with time zone NOT NULL,
                "Kind" smallint NOT NULL,
                "Status" smallint NOT NULL,
                "WorkerNodeId" uuid NOT NULL,
                "Count" bigint NOT NULL,
                "DurationCount" bigint NOT NULL,
                "DurationTotalMilliseconds" bigint NOT NULL,
                "DurationMaxMilliseconds" bigint NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );

            CREATE TABLE "ImageDistributionReferences" (
                "Id" uuid PRIMARY KEY,
                "DistributionRecordId" uuid NOT NULL,
                "Kind" smallint NOT NULL,
                "ResourceId" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_ImageDistributionReferences_ImageDistributionRecords"
                    FOREIGN KEY ("DistributionRecordId") REFERENCES "ImageDistributionRecords" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE "OperationalLogAggregates" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BucketStart" timestamp with time zone NOT NULL,
                "Level" character varying(15) NOT NULL,
                "Logger" character varying(250) NOT NULL,
                "Count" bigint NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );

            CREATE TABLE "TeamLabTrafficFlowAggregates" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BucketStart" timestamp with time zone NOT NULL,
                "RuntimeId" integer NOT NULL,
                "Generation" integer NOT NULL,
                "ShardId" integer NOT NULL,
                "NetworkId" integer NOT NULL,
                "Protocol" character varying(16) NOT NULL,
                "SourcePrefix" character varying(64) NOT NULL,
                "DestinationPrefix" character varying(64) NOT NULL,
                "FlowCount" bigint NOT NULL,
                "PacketCount" bigint NOT NULL,
                "Bytes" bigint NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );

            CREATE TABLE "TheoryQuestionTags" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DisplayName" character varying(64) NOT NULL,
                "NormalizedName" character varying(64) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );

            CREATE TABLE "TheoryQuestionTagBindings" (
                "QuestionId" integer NOT NULL,
                "TagId" integer NOT NULL,
                CONSTRAINT "PK_TheoryQuestionTagBindings" PRIMARY KEY ("QuestionId", "TagId"),
                CONSTRAINT "FK_TheoryQuestionTagBindings_Question"
                    FOREIGN KEY ("QuestionId") REFERENCES "TheoryQuestionBankItems" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_TheoryQuestionTagBindings_Tag"
                    FOREIGN KEY ("TagId") REFERENCES "TheoryQuestionTags" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX "UX_OperationalLogAggregates_Bucket_Level_Logger"
                ON "OperationalLogAggregates" ("BucketStart", "Level", "Logger");
            CREATE UNIQUE INDEX "UX_DeploymentLifecycleAggregates_Dimensions"
                ON "DeploymentLifecycleAggregates" ("BucketStart", "Kind", "Status", "WorkerNodeId");
            CREATE UNIQUE INDEX "UX_TeamLabFlowAggregates_Dimensions"
                ON "TeamLabTrafficFlowAggregates"
                ("BucketStart", "RuntimeId", "Generation", "ShardId", "NetworkId", "Protocol", "SourcePrefix", "DestinationPrefix");
            CREATE INDEX "IX_TeamLabFlowAggregates_Runtime_Generation_Bucket"
                ON "TeamLabTrafficFlowAggregates" ("RuntimeId", "Generation", "BucketStart");
            CREATE UNIQUE INDEX "UX_ImageDistributionReferences_Record_Kind_Resource"
                ON "ImageDistributionReferences" ("DistributionRecordId", "Kind", "ResourceId");
            CREATE INDEX "IX_ImageDistributionReferences_Kind_Resource"
                ON "ImageDistributionReferences" ("Kind", "ResourceId");
            CREATE UNIQUE INDEX "UX_TheoryQuestionTags_NormalizedName"
                ON "TheoryQuestionTags" ("NormalizedName");
            CREATE INDEX "IX_TheoryQuestionTagBindings_Tag_Question"
                ON "TheoryQuestionTagBindings" ("TagId", "QuestionId");
            CREATE INDEX "IX_DataGovernanceRuns_DataSet_StartedAt_Id"
                ON "DataGovernanceRuns" ("DataSet", "StartedAt" DESC, "Id" DESC);
            CREATE INDEX "IX_DataGovernanceRuns_Status_CompletedAt_Id"
                ON "DataGovernanceRuns" ("Status", "CompletedAt", "Id");

            CREATE TABLE "Logs_phase4"
                (LIKE "Logs" INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMMENTS)
                PARTITION BY RANGE ("TimeUtc");
            CREATE TABLE "TeamLabTrafficFlows_phase4"
                (LIKE "TeamLabTrafficFlows" INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STORAGE INCLUDING COMMENTS)
                PARTITION BY RANGE ("CapturedAt");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        throw new NotSupportedException(
            "Phase 4 database governance migrations are forward-only. Restore the pre-migration backup or use PITR.");
}
