<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <PublishTrimmed Condition="'$(RuntimeIdentifier)' != ''">true</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GZCTF.Test" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GZCTF.GuestTelemetry\GZCTF.GuestTelemetry.csproj" />
  </ItemGroup>
</Project>
