#!/usr/bin/env bash
set -Eeuo pipefail

umask 077

GZCTF_BASE_URL="${GZCTF_BASE_URL:?GZCTF_BASE_URL is required}"
GZCTF_SYNC_TOKEN_FILE="${GZCTF_SYNC_TOKEN_FILE:-/etc/gzctf/gateway-sync.token}"
NGINX_CONFIG_PATH="${NGINX_CONFIG_PATH:-/etc/nginx/stream-conf.d/gzctf-dynamic.conf}"
NGINX_BIN="${NGINX_BIN:-/usr/sbin/nginx}"
STATE_DIR="${STATE_DIR:-/var/lib/gzctf-gateway}"
LOCK_FILE="${LOCK_FILE:-/run/lock/gzctf-port-map-sync.lock}"

for command in curl jq awk flock install mktemp sha256sum; do
  command -v "$command" >/dev/null 2>&1 || {
    printf 'required command is missing: %s\n' "$command" >&2
    exit 1
  }
done

if [[ ! -r "$GZCTF_SYNC_TOKEN_FILE" ]]; then
  printf 'sync token file is not readable: %s\n' "$GZCTF_SYNC_TOKEN_FILE" >&2
  exit 1
fi

sync_token="$(tr -d '\r\n' < "$GZCTF_SYNC_TOKEN_FILE")"
if [[ -z "$sync_token" ]]; then
  printf 'sync token file is empty: %s\n' "$GZCTF_SYNC_TOKEN_FILE" >&2
  exit 1
fi

install -d -m 0700 "$STATE_DIR" "$(dirname "$LOCK_FILE")"
exec 9>"$LOCK_FILE"
flock -n 9 || exit 0

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

headers="$work_dir/headers"
port_map="$work_dir/port-map.json"
candidate="$work_dir/gzctf-dynamic.conf"
ack_response="$work_dir/ack-response.json"
base_url="${GZCTF_BASE_URL%/}"

curl --fail --silent --show-error --location \
  --connect-timeout 5 --max-time 20 --retry 2 --retry-all-errors \
  --header "Authorization: Bearer $sync_token" \
  --dump-header "$headers" \
  --output "$port_map" \
  "$base_url/api/internal/port-map"

revision="$(awk 'BEGIN { IGNORECASE=1 } /^X-GZCTF-Port-Map-Revision:/ { sub(/^[^:]+:[[:space:]]*/, ""); gsub(/\r/, ""); print; exit }' "$headers")"
if [[ ! "$revision" =~ ^[0-9a-f]{64}$ ]]; then
  printf 'port-map response did not contain a valid revision\n' >&2
  exit 1
fi

jq -e '
  type == "array" and
  all(.[];
    (.publicPort | type == "number" and . >= 1 and . <= 65535) and
    (.port | type == "number" and . >= 1 and . <= 65535) and
    (.ip | type == "string" and test("^[A-Za-z0-9._:-]+$")) and
    (.leaseId | type == "string" and test("^[0-9a-fA-F-]{36}$"))) and
  ([group_by(.publicPort)[] | select(length > 1)] | length == 0)
' "$port_map" >/dev/null

lease_ids="$(jq -c 'map(.leaseId) | unique | sort' "$port_map")"

acknowledge() {
  local succeeded="$1"
  local error_message="${2:-}"
  local payload http_status

  payload="$(jq -cn \
    --arg revision "$revision" \
    --argjson succeeded "$succeeded" \
    --argjson leaseIds "$lease_ids" \
    --arg error "$error_message" \
    '{revision: $revision, succeeded: $succeeded, leaseIds: $leaseIds}
     + (if $succeeded then {} else {error: $error} end)')"

  http_status="$(curl --silent --show-error --location \
    --connect-timeout 5 --max-time 20 --retry 2 --retry-all-errors \
    --header "Authorization: Bearer $sync_token" \
    --header 'Content-Type: application/json' \
    --request POST --data "$payload" \
    --output "$ack_response" --write-out '%{http_code}' \
    "$base_url/api/internal/port-map/ack")"

  if [[ "$http_status" == "409" ]]; then
    printf 'port map changed before acknowledgement; a later run will converge\n' >&2
    return 3
  fi
  if [[ ! "$http_status" =~ ^2 ]]; then
    printf 'port-map acknowledgement failed with HTTP %s\n' "$http_status" >&2
    return 1
  fi
}

{
  printf '# Generated by GZCTF gateway sync. Do not edit. Revision: %s\n' "$revision"
  while IFS=$'\t' read -r public_port host upstream_port; do
    [[ -n "$public_port" ]] || continue
    if [[ "$host" == *:* ]]; then
      host="[$host]"
    fi
    cat <<EOF
server {
    listen $public_port;
    proxy_connect_timeout 3s;
    proxy_timeout 3600s;
    proxy_pass $host:$upstream_port;
}
EOF
  done < <(jq -r 'sort_by(.publicPort)[] | [.publicPort, .ip, .port] | @tsv' "$port_map")
} > "$candidate"

candidate_hash="$(sha256sum "$candidate" | awk '{print $1}')"
state_file="$STATE_DIR/port-map.state"
current_revision=""
current_hash=""
if [[ -r "$state_file" ]]; then
  read -r current_revision current_hash < "$state_file" || true
fi

if [[ "$revision" == "$current_revision" && -r "$NGINX_CONFIG_PATH" ]]; then
  installed_hash="$(sha256sum "$NGINX_CONFIG_PATH" | awk '{print $1}')"
  if [[ "$installed_hash" == "$candidate_hash" && "$installed_hash" == "$current_hash" ]]; then
    acknowledge true
    exit 0
  fi
fi

install -d -m 0755 "$(dirname "$NGINX_CONFIG_PATH")"
had_previous=false
if [[ -e "$NGINX_CONFIG_PATH" ]]; then
  cp --preserve=mode,ownership,timestamps "$NGINX_CONFIG_PATH" "$work_dir/previous.conf"
  had_previous=true
fi
install -m 0644 "$candidate" "$NGINX_CONFIG_PATH"

restore_previous() {
  if [[ "$had_previous" == true ]]; then
    cp --preserve=mode,ownership,timestamps "$work_dir/previous.conf" "$NGINX_CONFIG_PATH"
  else
    rm -f "$NGINX_CONFIG_PATH"
  fi
}

if ! "$NGINX_BIN" -t >"$work_dir/nginx-test.log" 2>&1; then
  restore_previous
  acknowledge false "Public gateway configuration validation failed." || true
  printf 'nginx configuration validation failed; previous configuration restored\n' >&2
  exit 1
fi

if ! "$NGINX_BIN" -s reload >"$work_dir/nginx-reload.log" 2>&1; then
  restore_previous
  "$NGINX_BIN" -t >/dev/null 2>&1 && "$NGINX_BIN" -s reload >/dev/null 2>&1 || true
  acknowledge false "Public gateway reload failed." || true
  printf 'nginx reload failed; previous configuration restored\n' >&2
  exit 1
fi

acknowledge true
printf '%s %s\n' "$revision" "$candidate_hash" > "$state_file.tmp"
install -m 0600 "$state_file.tmp" "$state_file"
rm -f "$state_file.tmp"
